M48
; DRILL file {KiCad 9.0.6} date 2026-01-27T22:48:18+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-27T22:48:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.250
%
G90
G05
T1
X101.08Y-31.53
X109.08Y-31.53
T2
X71.39Y-82.41
X78.39Y-82.41
T3
X141.8Y-87.9
T4
X98.346Y-123.77
X111.046Y-123.77
X118.376Y-123.77
X131.076Y-123.77
M30
