[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
; upload_verify = false

; ESP32-S3-MINI-1U (typowo N4R2: 4MB flash + 2MB PSRAM)
; board_build.flash_mode = dio
; board_build.f_flash = 40000000L
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

; PSRAM włączona (QSPI)
board_build.arduino.memory_type = qio_qspi
board_build.extra_flags =
  -DBOARD_HAS_PSRAM

; Partycje i FS
board_build.partitions = default.csv
board_build.filesystem = littlefs

; Twoje biblioteki
lib_deps =
  adafruit/Adafruit ST7735 and ST7789 Library
  adafruit/Adafruit GFX Library
  adafruit/RTClib@^2.1.4

; Upload flags (zostawiam jak było)
upload_flags =
  --before=default_reset
  --after=hard_reset
;  --no-stub
